---
layout: post
title: 异步函数：Promise使用指南
categories: JavaScript
description: Promise详解
keywords: JavaScript
---
## 引言
一些基本概念:[异步编程](https://www.runoob.com/js/js-async.html)、[Promise](https://www.runoob.com/js/js-promise.html)  

## 详解  
### 基础内容  
Promise 构造函数只有一个参数，是一个函数，这个函数在构造之后会直接被异步运行，所以我们称之为起始函数。起始函数包含两个参数 resolve 和 reject。  

当 Promise 被构造时，起始函数会被异步执行：  

实例：  

```javascript
new Promise(function (resolve, reject) {
    console.log("Run");
});
```
这段程序会直接输出 Run。  

resolve 和 reject 都是函数，其中调用 resolve代表一切正常，reject 是出现异常时所调用的。  
Promise 类有 .then() .catch() 和 .finally() 三个方法，这三个方法的参数都是一个函数.  

.then() 正常执行函数序列，  

.catch() 异常处理序列，catch之前执行序列有任何异常都会直接跳到最近的catch 序列,  

.finally() 一定会执行的序列。  

即new Promise(resolve=>{}).then().catch(1).catch(2),若catch(1)前有异常,则由catch(1)捕获异常,若catch(1)内部有异常则由catch(2)捕获.  

```javascript
function Asynchronous(func, delay) {
    return new Promise((resolve, reject) => {
        setTimeout(() => {
            func();
            //必须调用resolve()声明异步操作完成
            resolve();
        }, delay);
    });
};
//定义函数简化后的通常方法
Asynchronous(() => {
    console.log(1);
}, 1000).then(() => {
    return Asynchronous(() => {
        console.log(2)
    }, 1000);
}).then(() => {
    Asynchronous(() => {
        console.log(3)
    }, 1000);
});
//使用线性编程完成异步操作
(async function () {
    await Asynchronous(() => {
        console.log(1);
    }, 1000);
    await Asynchronous(() => {
        console.log(2);
    }, 1000);
})();
```
该代码有一个缺陷,由setTimeout内产生的错误无法被catch()捕获.  

参见:[在旧式回调 API 中创建 Promise](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Using_promises#%E5%9C%A8%E6%97%A7%E5%BC%8F%E5%9B%9E%E8%B0%83_api_%E4%B8%AD%E5%88%9B%E5%BB%BA_promise)  

可以通过以下方式让setTimeout不产生错误:  
```javascript
function Asynchronous(func, delay) {
    return new Promise((resolve, reject) => {
        setTimeout(resolve, delay);
    }).then(() => {
        func();
    });
};
```
可使用异步函数特性:  
```javascript
async function Asynchronous(func, delay) {
    await new Promise((resolve, reject) => {
        setTimeout(resolve, delay);
    });
    func();
};
```
关键字 await 使函数等待 Promise,它<font color=Red>只能</font>在 async 函数中使用,async函数的返回值为一个Promise对象.  

then(),catch(),finall():  
```javascript
let info = [];
Asynchronous(() => {
    info.push("函数体正常执行");
    throw '发生错误';
}, 1000).then((t) => {
    info.push('{');
}).finally(() => {
    info.push('->');
}).catch((e) => {
    info.push('捕获:' + e);
}).then(() => {
    info.push('}');
    throw "then错误"
}).finally(() => {
    info.push('[');
}).catch((e) => {
    info.push('捕获:' + e);
}).finally(() => {
    info.push(']');
}).finally(() => {
    console.log(info.join(' '));
});
```
控制台:  
```
函数体正常执行 -> 捕获:发生错误 } [ 捕获:then错误 ]
```

### 传递内容  
要传递内容给then,则需要给resolve传入参数,resolve只接受一个参数,要在then传递内容给下一个then,则通过return即可.  

因此将函数改为:  
```javascript
function Asynchronous(func, delay, ...arg) {
    return new Promise((resolve, reject) => {
        setTimeout(resolve, delay, arg);
    }).then((i) => {
        return func(i);
    });
};
```
异步函数写法为:  
```javascript
async function Asynchronous(func, delay, ...arg) {
    const i = await new Promise((resolve, reject) => {
        setTimeout(resolve, delay, arg);
    });
    return func(i);
};
```

resolve传参示例:  
```javascript
function Asynchronous(func, delay, ...arg) {
    return new Promise((resolve, reject) => {
        setTimeout(resolve, delay, arg);
    }).then((i) => {
        return func(i);
    });
};
let a = {
    name: '小明',
    age: 18
};
let b = [1, 2, 3];
let c = new Map(Object.entries(a));
Asynchronous(arg => {
    console.log(...arg);
    return arg;
}, 1000, a, b, c).then(arg => {
    console.log(...arg);
    return arg;
}).then(arg => {
    console.log(...arg);
    return arg;
})
```
控制台:  
```javascript
{name: '小明', age: 18} [ 1, 2, 3 ] Map(2) {'name' => '小明', 'age' => 18}
{name: '小明', age: 18} [ 1, 2, 3 ] Map(2) {'name' => '小明', 'age' => 18}
{name: '小明', age: 18} [ 1, 2, 3 ] Map(2) {'name' => '小明', 'age' => 18}
```

new Promise对象时,通过resolve(arg)来传递内容到then,then通过return传递内容到后一个then.  

若中途出现错误被catch(e=>{}),则传递内容会丢失,在catch里只有e这个错误内容,通过return可以传值到下一个then.  

finally()不影响传递内容,但内容也传不到finally里,在finally里return也不会传递任何内容.  

new Promise对象时,通过reject(arg)来传递内容到catch,catch可以通过return传递内容到后一个then.就算catch后面紧接着还有一个catch也不会执行,因为没有报错.  

测试代码1:  
```javascript
function Asynchronous(func, delay, ...arg) {
    return new Promise((resolve, reject) => {
        setTimeout(resolve, delay, arg);
        // setTimeout(reject, delay, arg);
    }).then((i) => {
        return func(i);
    });
};
let a = {
    name: '小明',
    age: 18
};
let b = [1, 2, 3];
let c = new Map(Object.entries(a));
Asynchronous(arg => {
    console.log("func:", ...arg);
    return arg;
}, 1000, a, b, c).catch(arg => {
    console.log('catch1:', ...arg);
    return arg;
}).then(arg => {
    console.log('then1:', ...arg);
    return arg;
}).finally(arg => {
    console.log('finally:', arg);
    // throw '错误'
    return arg;
}).catch(arg => {
    console.log('catch2:', arg);
    return arg;
}).then(arg => {
    console.log('then2:', ...arg);
    return arg;
});
```
控制台:  
```javascript
func: { name: '小明', age: 18 } [ 1, 2, 3 ] Map(2) { 'name' => '小明', 'age' => 18 }
then1: { name: '小明', age: 18 } [ 1, 2, 3 ] Map(2) { 'name' => '小明', 'age' => 18 }
finally: undefined
then2: { name: '小明', age: 18 } [ 1, 2, 3 ] Map(2) { 'name' => '小明', 'age' => 18 }
```

测试代码2:  

在测试代码1的基础上,将finally内的注释取消,并将最后一个then展开语法删除(因为arg已经不是数组了):  

```javascript
func: { name: '小明', age: 18 } [ 1, 2, 3 ] Map(2) { 'name' => '小明', 'age' => 18 }
then1: { name: '小明', age: 18 } [ 1, 2, 3 ] Map(2) { 'name' => '小明', 'age' => 18 }
finally: undefined
catch2: 错误
then2: 错误
```

测试代码3:  
```javascript
function Asynchronous(func, delay, ...arg) {
    return new Promise((resolve, reject) => {
        // setTimeout(resolve, delay, arg);
        setTimeout(reject, delay, arg);
    }).then((i) => {
        return func(i);
    });
};
let a = {
    name: '小明',
    age: 18
};
let b = [1, 2, 3];
let c = new Map(Object.entries(a));
Asynchronous(arg => {
    console.log("func:", ...arg);
    return arg;
}, 1000, a, b, c).then(arg => {
    console.log('then1:', ...arg);
    return arg;
}).catch(arg => {
    console.log('catch1:', ...arg);
    return arg;
}).catch(arg => {
    console.log('catch2:', ...arg);
    return arg;
}).then(arg => {
    console.log('then2:', ...arg);
    return arg;
});
```

控制台:  
```javascript
catch1: { name: '小明', age: 18 } [ 1, 2, 3 ] Map(2) { 'name' => '小明', 'age' => 18 }
then2: { name: '小明', age: 18 } [ 1, 2, 3 ] Map(2) { 'name' => '小明', 'age' => 18 }
```
